#define    D@AM5AA              0x1
#define    D@AM5AB              0x0
#define    D@AM5AC              0x0
#define    D@AM5AD              0x0
#define    D@AM5AE              0x0
#define    D@AM5AL              0x0
#define    D@EncodingAlgorithm  0x1
#define    D@EncodeBitRate      0x4
#define    D@EncodeFrameCounter 0x6
#define    D@AudioFilter        0x0
#define    D@VSDPCM             0x1
